server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coursesystem?characterEncoding=utf-8&useSSL=false
    username: root
    password: 13458264160
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        max-active: -1
        max-idle: 8
        min-idle: 0
mybatis:
  type-aliases-package: com.swpu.coursesystem.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
jwt:
  secret: mysemysecretcret
  expiration: 2592000
###显示mybatis的sql语句执行日志信息###
logging:
  level:
    com:
      swpu:
        coursesystem:
          mapper: debug
